# Generated by Django 4.0.5 on 2022-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='default_blog.jpg', upload_to='blog_pics'),
        ),
    ]
