# Generated by Django 4.0.5 on 2022-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, default='default_blog.jpg', null=True, upload_to='blog_pics'),
        ),
    ]
